http_listen_addr: "0.0.0.0:6060"
introspection_addr: "0.0.0.0:6061"
log_level: info

indexer:
  connstring: "postgres://clair:clair@clair-db:5432/clair?sslmode=disable"
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true

matcher:
  connstring: "postgres://clair:clair@clair-db:5432/clair?sslmode=disable"
  max_conn_pool: 100
  run: ""
  migrations: true
  indexer_addr: "clair"

notifier:
  connstring: "postgres://clair:clair@clair-db:5432/clair?sslmode=disable"
  delivery_interval: "1m"
  poll_interval: "5m"
  migrations: true

auth:
  psk:
    key: "MTU5YzA4Y2ZkNzFmNTM0MjVmNTZlMmY4ZjEyYzQ2OTI3M2YzYjU4NzMwMTUzNDk0NjM4NzNhNzRlMzJjYTk1MQ=="
    iss: ["clairctl"]

# Updater configuration for vulnerability data
updaters:
  sets:
    - "rhel"
    - "debian"
    - "ubuntu"
    - "alpine"
    - "oracle"
    - "photon"
    - "aws"
    - "suse"
